#########################################
#                                       #
#         rbzAutoWelcome v1.7.0         #
#                                       #
#########################################

# The amount of ticks before the plugin forces players to say their wb/welcome message
# 20 ticks = 1 second
message-delay-min: 35
message-delay-max: 110

# The maximum length in characters (excluding '&' colour codes) of wb/welcome messages
# Bypass this using permission: rbzaw.bypass.maxlength
# Default: 64
max-message-length: 64

# Prevents AutoWelcome from sending welcome back messages for the same player repetitively in a short time span (ex. if someone is relogging a bunch of times)
prevent-same-player-wb-spam: true
# The minimum delay to wait between sending welcome back messages for the same player, in ticks
# Default: 300 (15s)
min-message-delay: 300

# Plugin hooks
hooks:
  essentials:
    # Enable the Essentials hook (only works if Essentials is found)
    enabled: true
    # Automatically welcome/ welcome back players who stop being AFK
    wb-returning-afk: true

# Placeholders - changing these will break existing uses in set auto-messages!
placeholders:
  # Replaced by a players' name when being welcome'd
  joining-player-name: "%p%"
  # Replaced by a players' display name (stripped of colorcodes) when being welcome'd. Useful if you want to use peoples nicknames instead of usernames
  joining-player-displayname: "%p-display%"

# Messages
messages:

  help:
    - "&8&m--------------------------------"
    - "&r         &6&lrbzAutoWelcome &8- &7Help"
    - "&r"
    - "&e/autowb"
    - "&7Displays this help menu"
    - "&e/autowb check &f<wb|welcome> [player]"
    - "&7Check your (or another player's) auto wb or welcome message"
    - "&e/autowb set &f<wb|welcome> <message|off>"
    - "&7Sets your auto wb or welcome message"
    - "&e/autowb setplayer &f<player> <wb|welcome> <message|off>"
    - "&7Sets another player's auto wb or welcome message"
    - "&e/autowb reload"
    - "&7Reloads the plugin's config"
    - "&8&m--------------------------------"

  # Generic messages
  incorrect-usage: "&c&lAUTOWB &8\u00BB &4Incorrect arguments! Command usage: &c%usage%"
  not-player: "&4[rbzAutoWelcome] You must be a player to execute this command!"
  no-permission: "&c&lAUTOWB &8\u00BB &4You do not have permission &c%permission% &4to do this!"
  unknown-player: "&c&lAUTOWB &8\u00BB &4Could not find player &c%target%&4!"
  exceeded-max-length: "&c&lAUTOWB &8\u00BB &4Maximum message length is &c%length% &4characters!"
  reload: "&6&lAUTOWB &8\u00BB &aSuccessfully reloaded &frbzAutoWelcome"

  wb:
    self:
      # Messages for setting or disabling your own auto-wb message
      enable: "&6&lAUTOWB &8\u00BB &aYour auto-wb message has been set to &f%msg%"
      disable: "&6&lAUTOWB &8\u00BB &cYour auto-wb message has been disabled."
      # Messages for checking your own auto-wb message
      check:
        success: "&6&lAUTOWB &8\u00BB &eYour auto-wb message is &f%msg%"
        fail: "&c&lAUTOWB &8\u00BB &4You have not set an auto-wb message!"
    other-player:
      # Messages for setting or disabling another player's auto-wb message
      enable: "&6&lAUTOWB &8\u00BB &aSet &f%target%&a's auto-wb message to &f%msg%"
      disable: "&6&lAUTOWB &8\u00BB &cDisabled &f%target%&c's auto-wb message."
      # Messages for checking another players' auto-wb message
      check:
        success: "&6&lAUTOWB &8\u00BB &f%player%&e's &eauto-wb message is &f%msg%"
        fail: "&c&lAUTOWB &8\u00BB &c%player% &4has not set an auto-wb message!"

  welcome:
    self:
      # Messages for setting or disabling your own auto-welcome message
      enable: "&6&lAUTOWB &8\u00BB &aYour auto-welcome message has been set to &f%msg%"
      disable: "&6&lAUTOWB &8\u00BB &cYour auto-welcome message has been disabled."
      # Messages for checking your own auto-welcome message
      check:
        success: "&6&lAUTOWB &8\u00BB &eYour auto-welcome message is &f%msg%"
        fail: "&c&lAUTOWB &8\u00BB &4You have not set an auto-welcome message!"
    other-player:
      # Messages for setting or disabling another player's auto-welcome message
      enable: "&6&lAUTOWB &8\u00BB &aSet &f%target%&a's auto-welcome message to &f%msg%"
      disable: "&6&lAUTOWB &8\u00BB &cDisabled &f%target%&c's auto-welcome message."
      # Messages for checking another player's auto-welcome message
      check:
        success: "&6&lAUTOWB &8\u00BB &f%player%&e's &eauto-welcome message is &f%msg%"
        fail: "&c&lAUTOWB &8\u00BB &c%player% &4has not set an auto-welcome message!"

# DO NOT TOUCH
config-version: 9