name: rbzAutoWelcome
version: 1.5.1
author: therbz
main: me.therbz.rbzautowelcome.AutoWelcome
api-version: 1.13
softdepend: [Essentials]
commands:
  autowb:
    description: Main rbzAutoWelcome command
    usage: /autowb
    aliases: [awb, rbzaw]
permissions:
  rbzaw.set:
    description: Set your own auto wb/welcome messages
    default: op
  rbzaw.others:
    description: Set other players' auto wb/welcome messages
    default: op
  rbzaw.check:
    description: Check your own auto wb/welcome messages
    default: op
  rbzaw.check.others:
    description: Check other players' auto wb/welcome messages
    default: op
  rbzaw.bypass.maxlength:
    description: Bypass max-message-length when setting
    default: op
  rbzaw.reload:
    description: Reload rbzAutoWelcome
    default: op