name: rbzAutoWelcome
version: 1.2.4
author: therbz
main: me.therbz.rbzautowelcome.AutoWelcome
api-version: 1.13
commands:
  autowb:
    description: Main rbzAutoWelcome command
    usage: /autowb
    aliases: [awb]